### ISSUE TITLE
fcrepo_wrapper unable to pull via proxy or not

### ISSUE THREAD

**Issue by rkhet** [projecthydra/hydra#99]
When attempting to run the fcrepo_wrapper with a specific port it appears the pull is failing.  W/ https_proxy set I get..
`rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:257:in 'open_http': Non-HTTP proxy URI: https://... (RuntimeError)`

W/ http_proxy set or no proxy defined..
`rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in 'initialize': Connection refused - connect(2) for "github.com" port 443 (Errno::ECONNREFUSED)`

**Comment by rkhet** [comment]
Seems something amis in

`rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb`:736:in `buffer_open' 

Failed w/ my https_proxy set.  Was able to pull .jar and gen md5 by hand and fcrepo_wrapper worked.

Also found..

[https://github.com/Homebrew/homebrew/issues/21679]

where, when _https_ and _http_ proxies are the same it's sugested that rather than setting _http_proxy_ and _https_proxy_ distinctly, set _http_proxy_ then..

`https_proxy=$http_proxy ; export https_proxy`

This also worked for me.
